## Project 3: House Price Prediction

Again we're going to do our next project with csv dataset only. This dataset it's little bit tricky if we compare to the previous projects datasets, so first we will check into it how the dataset look like and everything.

In [47]:
import pandas as pd

In [48]:
df = pd.read_csv("house_price_prediction.csv")

In [49]:
df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056

In the above dataset you can see that in some columns there's texts as data so we will found out what are the datas in columns which contains texts then we will map into integers.

In [51]:
print(df.describe())

                Id         Area     Bedrooms   Bathrooms       Floors  \
count  2000.000000  2000.000000  2000.000000  2000.00000  2000.000000
mean   1000.500000  2786.209500     3.003500     2.55250     1.993500
std     577.494589  1295.146799     1.424606     1.10899     0.809188
min       1.000000   501.000000     1.000000     1.00000     1.000000
25%     500.750000  1653.000000     2.000000     2.00000     1.000000
50%    1000.500000  2833.000000     3.000000     3.00000     2.000000
75%    1500.250000  3887.500000     4.000000     4.00000     3.000000
max    2000.000000  4999.000000     5.000000     4.00000     3.000000

         YearBuilt          Price
count  2000.000000    2000.000000
mean   1961.446000  537676.855000
std      35.926695  276428.845719
min    1900.000000   50005.000000
25%    1930.000000  300098.000000
50%    1961.000000  539254.000000
75%    1993.000000  780086.000000
max    2023.000000  999656.000000

In [52]:
df["Location"].value_counts()

Location
Downtown    558
Urban       485
Suburban    483
Rural       474
Name: count, dtype: int64

In Location there's only 4 inputs `Downtown`, `Urban`, `Suburban`, `Rural`

In [53]:
df["Condition"].value_counts()

Condition
Fair         521
Excellent    511
Poor         507
Good         461
Name: count, dtype: int64

In Condition column there's only 4 inputs `Fair`, `Excellent`, `Poor`, `Good`

In [54]:
df["Garage"].value_counts()

Garage
No     1038
Yes     962
Name: count, dtype: int64

In Garage column there's only two `Yes` and `No`

For this project we're going to take the 8 columns as inputs and with these columns we're going to predict the price. But, before that we're going to map the integers with the inputs

In [55]:
location_map = {"Downtown":0, "Urban":1, "Suburban":2, "Rural":3}
condition_map = {"Fair":0, "Excellent":1, "Poor":3, "Good":2}
garage_map = {"Yes":0, "No":1}

In [56]:
df["Location"] = df["Location"].map(location_map)

In [57]:
df["Location"].value_counts()

Location
0    558
1    485
2    483
3    474
Name: count, dtype: int64

In [58]:
df["Condition"] = df["Condition"].map(condition_map)

In [59]:
df["Condition"].value_counts()

Condition
0    521
1    511
3    507
2    461
Name: count, dtype: int64

In [60]:
df["Garage"] = df["Garage"].map(garage_map)

In [61]:
df["Garage"].value_counts()

Garage
1    1038
0     962
Name: count, dtype: int64

In [62]:
df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,0,1,1,149919
1,2,4272,5,4,3,1958,0,1,1,424998
2,3,3592,2,2,3,1938,0,2,1,266746
3,4,966,4,2,2,1902,2,0,0,244020
4,5,4926,1,4,2,1975,0,0,0,636056

From the above datasets now we're going to take the columns for inputs and outputs

input columns: `Area`, `Bedrooms`, `Bathrooms`, `Floors`, `YearBuilt`, `Location`, `Condition`, and `Garage`
output columns: `Price`

we're going to take `x` as inputs and `y` as output

In [63]:
x = df[['Area', 'Bedrooms', 'Bathrooms', 'Floors', 'YearBuilt', 'Location', 'Condition', 'Garage']].values

In [64]:
x

array([[1360,    5,    4, ...,    0,    1,    1],
       [4272,    5,    4, ...,    0,    1,    1],
       [3592,    2,    2, ...,    0,    2,    1],
       ...,
       [1062,    5,    1, ...,    3,    3,    1],
       [4062,    3,    1, ...,    1,    1,    0],
       [2989,    5,    1, ...,    2,    0,    1]], shape=(2000, 8))

In [65]:
y = df['Price'].values

In [66]:
y

array([149919, 424998, 266746, ..., 476925, 161119, 482525], shape=(2000,))

## Normalizing or Standardizing the Data

Without normalizing, the model thinks `Area` is way more important because its numbers are so big. like 

**Before Normalizing**

- `Area=2000` vs. `Bedrooms=3` the model might only care about `Area` because `2000` is so much bigger than `3`.
- It could miss that `3` bedrooms vs. `2` bedrooms matters too!

**After Normalizing**

- `Area` might go from `[2000, 1500]` to `[0.5, -0.5]` (average = 0, spread = 1)
- `Bedrooms` might go from `[3, 2]` to `[0.7, -0.7]`.
- Now they’re on the same scale `0.5` vs. `0.7` so the model listens to all clues fairly!

**Note:** for `YearBuilt` also same.

In [67]:
x = (x-x.mean(axis=0))/x.std(axis=0)

In [68]:
x

array([[-1.10147065,  1.40179052,  1.30556821, ..., -1.27070776,
        -0.42202954,  0.96269532],
       [ 1.14748543,  1.40179052,  1.30556821, ..., -1.27070776,
        -0.42202954,  0.96269532],
       [ 0.62231712, -0.70458141, -0.49832569, ..., -1.27070776,
         0.46272841,  0.96269532],
       ...,
       [-1.33161794,  1.40179052, -1.40027264, ...,  1.38305018,
         1.34748636,  0.96269532],
       [ 0.9853011 , -0.00245743, -1.40027264, ..., -0.38612178,
        -0.42202954, -1.03875025],
       [ 0.15661639,  1.40179052, -1.40027264, ...,  0.4984642 ,
        -1.3067875 ,  0.96269532]], shape=(2000, 8))

In [69]:
y_mean = y.mean()
y_std = y.std()

In [70]:
y = (y-y_mean)/y_std

Now we normalized data next, we need to convert the input and output to tensors like below:

In [71]:
import torch
import torch.nn as nn

In [72]:
x = torch.tensor(x, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32).reshape(-1, 1)

In [73]:
x

tensor([[-1.1015,  1.4018,  1.3056,  ..., -1.2707, -0.4220,  0.9627],
        [ 1.1475,  1.4018,  1.3056,  ..., -1.2707, -0.4220,  0.9627],
        [ 0.6223, -0.7046, -0.4983,  ..., -1.2707,  0.4627,  0.9627],
        ...,
        [-1.3316,  1.4018, -1.4003,  ...,  1.3831,  1.3475,  0.9627],
        [ 0.9853, -0.0025, -1.4003,  ..., -0.3861, -0.4220, -1.0388],
        [ 0.1566,  1.4018, -1.4003,  ...,  0.4985, -1.3068,  0.9627]])

In [74]:
y

tensor([[-1.4031],
        [-0.4077],
        [-0.9804],
        ...,
        [-0.2198],
        [-1.3626],
        [-0.1996]])

Next we're going to create a model

In [82]:
class HousePricePredictor(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(8, 64)
        self.layer2 = nn.Linear(64, 64)
        self.layer3 = nn.Linear(64, 32)
        self.layer4 = nn.Linear(32, 32)
        self.layer5 = nn.Linear(32, 16)
        self.layer6 = nn.Linear(16, 16)
        self.layer7 = nn.Linear(16, 8)
        self.layer8 = nn.Linear(8, 1)
        self.relu = nn.ReLU()
    def forward(self, x):
        x = self.relu(self.layer1(x))
        x = self.relu(self.layer2(x))
        x = self.relu(self.layer3(x))
        x = self.relu(self.layer4(x))
        x = self.relu(self.layer5(x))
        x = self.relu(self.layer6(x))
        x = self.relu(self.layer7(x))
        x = self.layer8(x)
        return x

In [83]:
model = HousePricePredictor()

In [84]:
criterion = nn.MSELoss()

In [85]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

Now let's start training

In [86]:
for epoch in range(200000):
    y_pred = model(x)
    loss = criterion(y_pred, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if (epoch+1)%5000 == 0:
        print(f"Try {epoch+1} Mistake: {loss.item():.4f}")

Try 5000 Mistake: 0.0420
Try 10000 Mistake: 0.0047
Try 15000 Mistake: 0.0447
Try 20000 Mistake: 0.0013
Try 25000 Mistake: 0.0046
Try 30000 Mistake: 0.0004
Try 35000 Mistake: 0.1236
Try 40000 Mistake: 0.0013
Try 45000 Mistake: 0.0002
Try 50000 Mistake: 0.0004
Try 55000 Mistake: 0.2881
Try 60000 Mistake: 0.0002
Try 65000 Mistake: 0.0001
Try 70000 Mistake: 0.0001
Try 75000 Mistake: 0.0000
Try 80000 Mistake: 0.0017
Try 85000 Mistake: 0.0002
Try 90000 Mistake: 0.0000
Try 95000 Mistake: 0.0000
Try 100000 Mistake: 0.0001
Try 105000 Mistake: 0.0032
Try 110000 Mistake: 0.0000
Try 115000 Mistake: 0.0005
Try 120000 Mistake: 0.0000
Try 125000 Mistake: 0.0000
Try 130000 Mistake: 0.0003
Try 135000 Mistake: 0.0000
Try 140000 Mistake: 0.0000
Try 145000 Mistake: 0.0000
Try 150000 Mistake: 0.0000
Try 155000 Mistake: 0.0000
Try 160000 Mistake: 0.0000
Try 165000 Mistake: 0.0000
Try 170000 Mistake: 0.0008
Try 175000 Mistake: 0.0000
Try 180000 Mistake: 0.0000
Try 185000 Mistake: 0.0002
Try 190000 Mistake: 0.0000
Try 195000 Mistake: 0.0002
Try 200000 Mistake: 0.0000

In [87]:
with torch.no_grad():
    y_pred = model(x[:5])
    y_pred_dollars = y_pred * y_std + y_mean  # Back to dollars
    y_dollars = y[:5] * y_std + y_mean
    print("Guessed Prices:", y_pred_dollars.flatten().tolist())
    print("Real Prices:", y_dollars.flatten().tolist())

Guessed Prices: [150098.25, 424516.375, 265931.96875, 243310.0, 636051.0625]
Real Prices: [149919.03125, 424998.03125, 266746.03125, 244020.03125, 636056.0]